ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 60.0
    two_d_mode: true
    diagnostics_agg: true

    # map_frame: "map"                      # 固定参考框架
    base_link_frame: "base_link_filter"   # 机器人基座的框架
    world_frame: "map"                    # 世界坐标的参考
    odom_frame:  "map"
    imu0: /wht101/imu
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, true,
                  false, false, true,
                  false, false, true]
    pose0: /rtk/antenna/pose
    pose0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]



    imu0_differential: true
    imu0_relative: true


    # twist0: /rtk/antenna/twist
    # twist0_config: [false, false, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, true,
    #                false, false, false]
    # twist0_differential: false  # 使用差分处理，确保速度相对于最近的位置测量
    # twist0_relative: false



    # twist1: /motor/baselink/twist
    # twist1_config: [false, false, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, true,
    #                false, false, false]
    # twist1_differential: false  # 使用差分处理，确保速度相对于最近的位置测量
    # twist1_relative: false

    transform_timeout: 0.0
    transform_time_offset: 0.0
